### ISSUE TITLE
sleepy time isn't an integer

### ISSUE THREAD

**Issue by biemond** [fiddyspence/puppet-sleep#1]
Hi,

great work and hope you can help me with this.
Somehow I can't cast the manifest parameter or hiera lookup to an integer, I tried stdlib or multiply with 1 but nothing helps.  Only defining a var inside the manifest works 

off course I can make a custom parser function but you hope you can try to cast it to an integer and raise an error when it fails.

```
  aaaa(
      $sleep   = hiera('wls_nodemanager_sleep'         , 20), # default sleep time
  ) {

      sleep { "wake up ${title}":
        bedtime       => $sleep,
```

Cheers

Edwin

**Comment by adamjk-dev** [comment]
Agreed on this, is there a way that your module can try to cast a string (something read from hiera) into an integer for validation?

**Comment by fiddyspence** [comment]
Oh - you're running foul of the type parameter validation doing it's job I assume, or are you saying that the munge/validate isn't working?

https://github.com/fiddyspence/puppet-sleep/blob/master/lib/puppet/type/sleep.rb#L14-L20

Given your code though, I can't see a problem with

```
  sleep { "wake up ${title}":
    bedtime       => $sleep,
```

**Comment by biemond** [comment]
Indeed,

your code looks good but maybe validate is executed before munge

**Comment by adamjk-dev** [comment]
According to the documentation, values are always validated before munged:

https://docs.puppetlabs.com/guides/custom_types.html

"
The default validate method looks for values defined using newvalues and if there are any values defined it accepts only those values (this is exactly how allowed values are validated). The default munge method converts any values that are specifically allowed into symbols. If you override either of these methods, note that you lose this value handling and symbol conversion, which you’ll have to call super for.

Values are always validated before they’re munged.

Lastly, validation and munging only\* happen when a value is assigned. They have no role to play at all during use of a given value, only during assignment.
"

**Comment by adamjk-dev** [comment]
Did we do any further digging on this? The custom types documentation said that values are validated before they are munged. This is likely why we were hitting the issue here.

https://docs.puppetlabs.com/guides/custom_types.html#validation-and-munging

**Comment by adamjk-dev** [comment]
Biemond, did you try using math in your orawls module after the hiera lookup? Hiera by default treats things as strings unless a math operation is performed.

https://github.com/biemond/biemond-orawls/blob/f88fc1a5712d70589a15b8734ec9270811d60bac/manifests/nodemanager.pp#L29

Something like: 

```
$sleep = hiera('wls_nodemanager_sleep' , 20) * 1, # default sleep time
```

(Note: The above example did not work for me)

**Comment by adamjk-dev** [comment]
I was able to get it to work locally for me by changing the validate function to be as follows:

```
validate do |zzzz|
  fail("sleep time isn't an integer (#{zzzz})!") unless Integer(zzzz)
end
```

This worked for the following hiera values:

```
wls_nodemanager_sleep: "80"
wls_nodemanager_sleep: 80
```

And it failed in hiera for:

```
wls_nodemanager_sleep: true
wls_nodemanager_sleep: "blah"
```

**Comment by fiddyspence** [comment]
Yeah - I had a bit of an epiphany last night about that regex only working on a string

Now - the question is what does your environment look like, because this worked for me before with Puppet 3.7.4 on EL6 using system ruby which suggests that there's something about your setup that has changed the way Puppet yields the value into the validate block (i.e. I was getting it as a string, and you clearly were not)

I've merged that edit into master - if you feel like giving it a crack, I'll stuff a new version on the Forge

**Comment by adamjk-dev** [comment]
Glad to hear it, as I think when I checked my variable for zzzz was going in as a 'Fixnum'.

```
# /opt/puppet/bin/puppet --version
3.6.2 (Puppet Enterprise 3.3.1)
# /opt/puppet/bin/hiera --version
1.3.3
```

I tried out your latest module version '1.2.0' and it seemed to work for me. Thanks for updating this, I appreciate it!

I presume we can close the issue now...

**Comment by biemond** [comment]
thanks
